### ISSUE TITLE
Sidebar blank on the white mode

### ISSUE THREAD

**Issue by an-jorge** [IldySilva/SnapInk#12]
The text in the sidebar is blank in white mode, and the text only appears if I turn my computer on to dark mode.
I tested in Chrome -V 129.0.6668.100 (64 bits) and Firefox -V 131.0.3 (64-bit) 

![Captura de ecrã de 2024-10-23 05-26-53](https://github.com/user-attachments/assets/bb462585-171b-4014-8ceb-d10c070cebba)
![Captura de ecrã de 2024-10-23 05-26-23](https://github.com/user-attachments/assets/d3d88f8e-1578-4a1f-90fb-580f54cf200b)

**Comment by IldySilva** [comment]
Nice catch @an-jorge 
Thank you
