### ISSUE TITLE
 Reducing the minimum Dart SDK version

### ISSUE THREAD

**Issue by paulinofonsecas** [IldySilva/SnapInk#8]
I would like to suggest reducing the minimum Dart SDK version specified in the pubspec.yaml file. Currently, the package requires version >=3.5.3, but many projects, including mine, are still using earlier versions like 3.5.2 or lower. Lowering the minimum SDK version would allow more developers, who have not yet migrated to newer versions of Dart, to adopt this package.

Impact: My project, which is using Dart SDK 3.5.2, is unable to integrate this package due to the minimum SDK version constraint. I believe many other developers might face a similar issue, particularly in environments where SDK upgrades are restricted.

**Comment by IldySilva** [comment]
Do you want to work on this?

**Comment by paulinofonsecas** [comment]
Yes, I will work on this
